### ISSUE TITLE
[서버이슈]검색>TV프로그램 검색 전문 오류 관련

### ISSUE THREAD

**Issue by moriarty-dean** [LambertPark/I_NScreen#107]
검색>TV프로그램 검색 전문에서 
totalCount 값을 초과하는 페이지 값을 넣어도 데이터가 들어옴.

ex>
아래의 전문을 보낼 경우, 
totalCount의 값은 14인데, 페이지 당 갯수(limit)가 10 인 상태에서 10번째 페이지(offset)을 호출하면 
데이터가 들어옴

http://58.141.255.69:8080/nscreen/searchSchedule.xml?areaCode=0&limit=10&offset=5&searchString=생명의%20양식&terminalKey=6840A4B3A93ADB1146F19A4E3D34439E&version=1

<response>
<version>1.0.0</version>
<transactionId>-1</transactionId>
<resultCode>100</resultCode>
<errorString/>
<totalCount>14</totalCount>
<scheduleItem>
<channelId>101</channelId>
<channelNumber>701</channelNumber>
<channelName>CBS</channelName>
<channelInfo>SD,HD</channelInfo>
<channelLogoImg>http://58.141.255.69:8080/logo/101.png</channelLogoImg>
<channelProgramID>S369193054</channelProgramID>
<channelProgramTime>2015-12-10 06:00:00</channelProgramTime>
<channelProgramTitle>생명의 양식<서산성결(이기용)></channelProgramTitle>
<channelProgramSeq>369193054</channelProgramSeq>
<channelProgramGrade>모두 시청</channelProgramGrade>
<channelProgramHD>NO</channelProgramHD>
</scheduleItem>
<scheduleItem>
<channelId>101</channelId>
<channelNumber>701</channelNumber>
<channelName>CBS</channelName>
<channelInfo>SD,HD</channelInfo>
<channelLogoImg>http://58.141.255.69:8080/logo/101.png</channelLogoImg>
<channelProgramID>S369193079</channelProgramID>
<channelProgramTime>2015-12-10 19:40:00</channelProgramTime>
<channelProgramTitle>생명의 양식<순복음영산(강영선)></channelProgramTitle>
<channelProgramSeq>369193079</channelProgramSeq>
<channelProgramGrade>모두 시청</channelProgramGrade>
<channelProgramHD>NO</channelProgramHD>
</scheduleItem>
<scheduleItem>
.
.
.
.
.
.
.

**Comment by benjamincho** [comment]
이슈닫습니다.
