### ISSUE TITLE
[서버이슈] 녹화 예약 전문 관련

### ISSUE THREAD

**Issue by moriarty-dean** [LambertPark/I_NScreen#115]
녹화요청 전문 호출시, resultCode가 207로 들어오는 경우가 종종 발생함.

=========================
ex)하단은 [kbs 나를 돌아봐] 녹화 요청시 로그로 아래와 같이 resultCode 값이 [207]로 들어옴.

http://58.141.255.80/smapplicationserver/SetRecordSeriesReserve.asp?ChannelId=152&StartTime=2015-12-11%2021%3A30%3A00&deviceId=BFB84ABE-1470-43DD-A5B8-ECB40F91CA9A&seriesId=M614021506&terminalKey=6840A4B3A93ADB1146F19A4E3D34439E&version=1

2015-12-10 11:08:18:383 I_NScreen[387:39542] 녹화예약 설정 시리즈 = [(
        {
        __name = response;
        transactionId = 1;
        resultCode = 207;
        errString = Internal Processing Error;
        version = SmartMobile_v1.0.0;
    }

)]

**Comment by benjamincho** [comment]
문의전달하여 이슈닫습니다.
