### ISSUE TITLE
[서버이슈] 녹화예약 취소 전문 관련

### ISSUE THREAD

**Issue by moriarty-dean** [LambertPark/I_NScreen#116]
녹화>녹화 예약 관리

임의의 녹화 예약 등록된 시리즈 A를 [녹화 예약 취소(SetRecordCancelReserve)] 전문을 호출하여,

해당 A시리즈를 녹화 취소한 후에, [예약 녹화물 리스트(getrecordReservelist)] 전문을 호출시

삭제된 시리즈 A를 포함하여 예약 녹화물 리스트를 반환함.

다시한번 [예약 녹화물 리스트(getrecordReservelist)] 전문을 호출하면,

시리즈 A가 포함되지 않은 예약 녹화물 리스트를 반환함.

============================================

ex> 하단은 녹화예약된 [KBS2_HD 두리둥실 뭉게공항 2] 시리즈를 녹화 취소 한 후(1),
       예약 녹화물 리스트를 조회 시 [KBS2_HD 두리둥실 뭉게공항 2]가 포함되어 들어왔다가 (2),
       다시 예약 녹화물 리스트를 조회 시 [KBS2_HD 두리둥실 뭉게공항 2]가 제거된 목록을 반환(3)
      하는 로그입니다.

(1) -------------------------------------------------------------------------------------------------------------------------------
2015-12-10 11:30:06.162 I_NScreen[411:47629] request : <NSMutableURLRequest: 0x1415d2970> { URL: http://58.141.255.80/smapplicationserver/SetRecordCancelReserve.asp?ChannelId=152&ReserveCancel=1&StartTime=2015-12-11%2016%3A00%3A00&deviceId=BFB84ABE-1470-43DD-A5B8-ECB40F91CA9A&seriesId=M3130927342&terminalKey=6840A4B3A93ADB1146F19A4E3D34439E&version=1 }
2015-12-10 11:30:07:258 I_NScreen[411:47629] 녹화에약취소 = [(
        {
        __name = response;
        transactionId = 1;
        resultCode = 100;
        version = SmartMobile_v1.0.0;
    }

)}

(2) -------------------------------------------------------------------------------------------------------------------------------
2015-12-10 11:30:07.503 I_NScreen[411:47629] request : <NSMutableURLRequest: 0x141314db0> { URL: http://58.141.255.80/smapplicationserver/getrecordReservelist.asp?deviceId=BFB84ABE-1470-43DD-A5B8-ECB40F91CA9A&terminalKey=6840A4B3A93ADB1146F19A4E3D34439E&version=1 }
2015-12-10 11:30:09:212 I_NScreen[411:47629] 예약 녹화물 리스트 = [(
        {
        __name = response;
        transactionId = 1;
        resultCode = 100;
        Reserve_Item =     (
                {
            Channel_logo_img = http://58.141.255.69:8080/logo/152.png;
            RecordingType = 0;
            ChannelName = KBS2_HD;
            RecordHD = YES;
            RecordPaytype = N;
            ChannelId = 152;
            ProgramName = 두리둥실 뭉게공항 2(15회)(재);
            OverlapId = 0;
            RecordStartTime = 2015-12-11 16:00:00;
            RecordStatus = N;
            ChannelNo = 7;
            SeriesId = M3130927342;
            RecordEndTime = 2015-12-11 16:30:00;
        }
,
                {
            Channel_logo_img = http://58.141.255.69:8080/logo/152.png;
            RecordingType = 1;
            ChannelName = KBS2_HD;
            RecordHD = YES;
            RecordPaytype = N;
            ChannelId = 152;
            ProgramName = 두리둥실 뭉게공항 2;
            OverlapId = 0;
            RecordStartTime = 0;
            RecordStatus = N;
            ChannelNo = 7;
            SeriesId = M3130927342;
            RecordEndTime = 2015-12-11 16:30:00;
        }
,
                {
            Channel_logo_img = http://58.141.255.69:8080/logo/152.png;
            RecordingType = 0;
            ChannelName = KBS2_HD;
            RecordHD = YES;
            RecordPaytype = N;
            ChannelId = 152;
            ProgramName = TV소설 별이 되어 빛나리;
            OverlapId = 0;
            RecordStartTime = 2015-12-14 09:00:00;
            RecordStatus = N;
            ChannelNo = 7;
            SeriesId = M614031796;
            RecordEndTime = 2015-12-14 09:40:00;
        }
,
                {
            Channel_logo_img = http://58.141.255.69:8080/logo/152.png;
            RecordingType = 0;
            ChannelName = KBS2_HD;
            RecordHD = YES;
            RecordPaytype = N;
            ChannelId = 152;
            ProgramName = TV소설 별이 되어 빛나리(74회);
            OverlapId = 0;
            RecordStartTime = 2015-12-11 09:00:00;
            RecordStatus = N;
            ChannelNo = 7;
            SeriesId = M614031796;
            RecordEndTime = 2015-12-11 09:40:00;
        }
,
                {
            Channel_logo_img = http://58.141.255.69:8080/logo/152.png;
            RecordingType = 1;
            ChannelName = KBS2_HD;
            RecordHD = YES;
            RecordPaytype = N;
            ChannelId = 152;
            ProgramName = TV소설 별이 되어 빛나리;
            OverlapId = 0;
            RecordStartTime = 0;
            RecordStatus = N;
            ChannelNo = 7;
            SeriesId = M614031796;
            RecordEndTime = 2015-12-14 09:40:00;
        }

    );
        version = SmartMobile_v1.0.0;
    }

)]

(3) -------------------------------------------------------------------------------------------------------------------------------
2015-12-10 11:31:04.625 I_NScreen[411:47629] request : <NSMutableURLRequest: 0x1415a3640> { URL: http://58.141.255.80/smapplicationserver/getrecordReservelist.asp?deviceId=BFB84ABE-1470-43DD-A5B8-ECB40F91CA9A&terminalKey=6840A4B3A93ADB1146F19A4E3D34439E&version=1 }
2015-12-10 11:31:05:429 I_NScreen[411:47629] 예약 녹화물 리스트 = [(
        {
        __name = response;
        transactionId = 1;
        resultCode = 100;
        Reserve_Item =     (
                {
            Channel_logo_img = http://58.141.255.69:8080/logo/152.png;
            RecordingType = 0;
            ChannelName = KBS2_HD;
            RecordHD = YES;
            RecordPaytype = N;
            ChannelId = 152;
            ProgramName = TV소설 별이 되어 빛나리;
            OverlapId = 0;
            RecordStartTime = 2015-12-14 09:00:00;
            RecordStatus = N;
            ChannelNo = 7;
            SeriesId = M614031796;
            RecordEndTime = 2015-12-14 09:40:00;
        }
,
                {
            Channel_logo_img = http://58.141.255.69:8080/logo/152.png;
            RecordingType = 0;
            ChannelName = KBS2_HD;
            RecordHD = YES;
            RecordPaytype = N;
            ChannelId = 152;
            ProgramName = TV소설 별이 되어 빛나리(74회);
            OverlapId = 0;
            RecordStartTime = 2015-12-11 09:00:00;
            RecordStatus = N;
            ChannelNo = 7;
            SeriesId = M614031796;
            RecordEndTime = 2015-12-11 09:40:00;
        }
,
                {
            Channel_logo_img = http://58.141.255.69:8080/logo/152.png;
            RecordingType = 1;
            ChannelName = KBS2_HD;
            RecordHD = YES;
            RecordPaytype = N;
            ChannelId = 152;
            ProgramName = TV소설 별이 되어 빛나리;
            OverlapId = 0;
            RecordStartTime = 0;
            RecordStatus = N;
            ChannelNo = 7;
            SeriesId = M614031796;
            RecordEndTime = 2015-12-14 09:40:00;
        }

    );
        version = SmartMobile_v1.0.0;
    }

)]

**Comment by benjamincho** [comment]
문의전달하여 이슈닫습니다.
