### ISSUE TITLE
84. 'PROGRESS BAR 노출 및 진행 상태 노출 되지않음.

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#12]
[보고일]
2015.11.19

[추적이슈번호]
84

[재현경로]
1. 씨앤앰 모바일 TV App 실행

[기대결과]
'PROGRESS BAR 노출 및 진행 상태 노출되어야함.
** LOADING 이미지 표출 시 앱 단에서 PRE-LOADING 되는 데이터 형태는 추후 개발 단에서 정의

[현재증상]
'PROGRESS BAR 노출 및 진행 상태 노출 되지않음.

**Comment by benjamincho** [comment]
[검토일]
2015.12.01

[검토의견]
1. 단순기능 이나, 앱성격상 앱 구동시 서버로 부터 받는 데이타가 없어서 프로그레스바의 필요성에 대해서 기획에서 재검토가 필요함.
2. 작업을 할 경우 디자인검토 필요

0.5day	마이너	단위기능

**Comment by benjamincho** [comment]
이슈 종료합니다.

**Comment by MinJaeHun** [comment]
2015.12.05  캐스트이즈로 closing 처리 요청
