### ISSUE TITLE
197. VOD 검색 시 표출되는 VIRTUAL KEYBOARD 에서 '돋보기' 아이콘이 아닌 'Done' 버튼으로 표출됨. *안드로이드의 경우 '돋보기' 버튼으로 표출됨

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#127]
[보고일자]
2015.12.08

[빌드버전]
1.0.5

[재현경로]
1.검색버튼 > 검색 할 컨텐츠 타이틀 입력
2.표촐되는 VIRTUAL KEYBOARD 검색버튼확인

[예상결과]
'컨텐츠 타이틀 입력 후 표출되는  VIRTUAL KEYBOARD '에 Done 버튼이 아닌 '돋보기' 아이콘으로 변경되어야함.

[현재증상]
VOD 검색 시 표출되는 VIRTUAL KEYBOARD 에서 '돋보기' 아이콘이 아닌 'Done' 버튼으로 표출됨.
*안드로이드의 경우 '돋보기' 버튼으로 표출됨

**Comment by benjamincho** [comment]
아이폰의 경우 , 돋보기 아이콘이 아닌 [검색] 텍스트가 제공됨.[검색]텍스트로는 변경 가능

**Comment by benjamincho** [comment]
IOS키보드는 클라이언트 보다는 사용자의 설정에 더 영향을 받습니다.
또한 해당 아이콘처리는 클라이언트가 제어할 수 없는 영역입니다.

**Comment by moriarty-dean** [comment]
검색으로 수정.

**Comment by benjamincho** [comment]
이전버전에 수정되었으나 릴리즈노트 누락으로 5차개선에 재반영
