### ISSUE TITLE
85. '입력 비밀번호가 상이 할 때, 비밀번호 입력 필드에 포커스 이동 시 기존 입력 내용 초기화 되지 않음.

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#13]
[보고일]
2015.11.19

[추적이슈번호]
85

[재현경로]
1. 씨앤앰 모바일 TV App 실행
2. 셋탑박스 등록 구매 비밀번호 설정 페이지
3. 구매 비밀번호 신규설정 , 구매비밀번호 입력화인' 입력창에 비밀번호 상이하게 입력
4. 화면확인

[기대결과]
'입력 비밀번호가 상이 할 때, 비밀번호 입력 필드에 포커스 이동 시 기존 입력 내용 초기화 되어야함.

[현재증상]
'입력 비밀번호가 상이 할 때, 비밀번호 입력 필드에 포커스 이동 시 기존 입력 내용 초기화 되지 않음.

**Comment by benjamincho** [comment]
[검토일]
2015.12.01

[검토의견]
0.2day	마이너	단위기능

**Comment by benjamincho** [comment]
정확한 기능설명을 다시 요청하겠습니다.
이슈 재오픈합니다.

**Comment by MinJaeHun** [comment]
2015.12.05 캐스트이즈로 closing 처리 또는 정확한 가이드 요청

**Comment by benjamincho** [comment]
비밀번호 입력 후 done버튼 처치시 키패드 유지되면서 입력값 초기화 하도록 수정한다고 가이드 받았습니다.

**Comment by MinJaeHun** [comment]
[2015.12.07] 캐스트이즈, 고도화 시점 반영하는 것으로 C&M과 협의

**Comment by MinJaeHun** [comment]
[2015.12.08] QC, 이슈 재현됨
