### ISSUE TITLE
212. VOD 컨텐츠 결제 시 표출되는 VIRTUAL KEYBOARD 에 '다음문장' 으로 표기됨

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#132]
[보고일자]
2015.12.08

[빌드버전]
1.0.5

[재현경로]
1,.VOD 컨텐츠 구매하기 선택
2.결제하기 선택 > 표출되는 VIRTUAL KEYBOARD 에서 '다음문장' 확인

[예상결과]
표출되는 VIRTUAL KEYBOARD 에 '다음문장' 이 아닌 '확인' 버튼으로 변경되어야함.

[현재증상]
VOD 컨텐츠 결제 시 표출되는 VIRTUAL KEYBOARD 에 '다음문장' 으로 표기됨

**Comment by moriarty-dean** [comment]
[Done]으로만 가능함.
