### ISSUE TITLE
223. App 내 Default 폰트 사이즈 모두 동일하지 않음

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#138]
[보고일자]
2015.12.08

[빌드버전]
1.0.5

[재현경로]
1.VOD 구매목록 내에 폰트 사이즈 확인

[예상결과]
'App 내 Default 폰트 사이즈 모두 동일하게 수정 되어야 함
(ex : 포스터 목록 하단 VOD명, 구매목록…)

[현재증상]
'App 내 Default 폰트 사이즈 모두 동일하지 않음

**Comment by moriarty-dean** [comment]
디폴트 폰트 사이즈와 디폴트 폰트 사이즈가 적용되어야 하는 UI목록 필요.

**Comment by benjamincho** [comment]
최초 가이드된 폰트사이즈의 약 1/2 값으로 처리하면 됩니다.
ex. 38 -> 17

**Comment by benjamincho** [comment]
52pt ▶︎ 25pt (보내주신 폰트별화면에는 24pt 사이즈가 없던데 혹시 가능하시면 24pt로 될까요?-_ ㅠ)
50pt ▶︎ 22pt
44pt ▶︎ 20pt
42pt ▶︎ 19pt
40pt ▶︎ 18pt
39pt ▶︎ 17pt
38pt ▶︎ 17pt
37pt ▶︎ 16pt
36pt ▶︎ 16pt
34pt ▶︎ 15pt
33pt ▶︎ 14pt
32pt ▶︎ 14pt
31pt ▶︎ 13pt
30pt ▶︎ 13pt
29pt ▶︎ 13pt
28pt ▶︎ 12pt
27pt ▶︎ 12pt
