### ISSUE TITLE
237. 타이틀이 긴 TV 전용 VOD 상세 페이지 내 TV 시청 가능 안내 문구 텍스트 좌우 잘림 (iPhone 5

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#143]
[보고일자]
2015.12.09

[빌드버전]
1.0.6

[재현경로]
1. iPhone 5 확인
2. 타이틀이 긴 TV 전용 VOD 상세 페이지
3. TV 시청 가능 안내 문구 확인

[예상결과]
타이틀이 긴 TV 전용 VOD 상세 페이지 내 TV 시청 가능 안내 문구 텍스트 정상 표기 되어야 함

[현재증상]
타이틀이 긴 TV 전용 VOD 상세 페이지 내 TV 시청 가능 안내 문구 텍스트 좌우 잘림 (iPhone 5)

**Comment by moriarty-dean** [comment]
5는 화면이 작아서 문구가 길어질 경우, 화면내에 전체 문구를 표시하는데 무리가 있습니다.

타이틀, 가격 쪽 문구에 가변적으로 폰트사이즈를 적용하여, 

문구가 길어질 경우 폰트사이즈 최소 8까지 축소 적용하게 수정했습니다.

그 이상으로 문구가 길어질 경우 말줄임표로 표출되게 됩니다.

**Comment by benjamincho** [comment]
QC : 현재 ‘iPhone5’ 단말기가 보유중이지 않아 추후 에 확인이 가능합니다.

**Comment by benjamincho** [comment]
QC : 현재 ‘iPhone5’ 단말기가 보유중이지 않아 추후 에 확인이 가능합니다.
