### ISSUE TITLE
88. 'VOD 시청중 단말기에서 전원버튼 선택(Sleep mode) 진입 후 Sleep mode 해제 시 재생 안됨.

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#15]
[보고일]
2015.11.19

[추적이슈번호]
88

[재현경로]
1. 씨앤앰 모바일 TV App 실행
2. VOD 컨텐츠 시청하기 > VOD 재생중 디바이스 전원버튼(Sleep mode) 진입 후 Sleep mode 해제  > '▶' 버튼 터치
3. 재생확인

[기대결과]
'▶' 버튼 터치 시 해당 VOD 재생되어야함.

[현재증상]
'VOD 시청중 단말기에서 전원버튼 선택(Sleep mode) 진입 후 해제 시 재생 안됨.

**Comment by benjamincho** [comment]
[검토일]
2015.12.01

[검토의견]
민대표님께서 확인하신 내용으로 아이폰은 앱이 백그라운드로 이동했다가 포어그라운드로 다시 돌아올 때 동영상이 pause상태로 변경되고, 다시 재생됩니다.

사용자의 판단에 따라 다시 재생하도록 현행 유지하고 진행한다고 확인하였습니다.

해당 이슈 종료합니다.

**Comment by MinJaeHun** [comment]
[2015.12.05] 현상 재검토 후 적용 또는 closing 요청 등 계획 확정 예정

**Comment by MinJaeHun** [comment]
[2015.12.05] 죄송합니다. QC issue list에서 closed 된 항목입니다. (2015.12.02 v1.03)
