### ISSUE TITLE
89. 'VOD 컨텐츠 구매 결제 완료 후 즉시 시청되지 않음.

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#16]
[보고일]
2015.11.19

[추적이슈번호]
89

[재현경로]
1. 씨앤앰 모바일 TV App 실행
2. VOD 컨텐츠 구매 결제 완료
3. 상태확인

[기대결과]
'VOD 컨테츠 구매 결제 완료 후 즉시 시청되어야함.

[현재증상]
'VOD 컨텐츠 구매 결제 완료 후 즉시 시청되지 않음.

**Comment by benjamincho** [comment]
[검토일]
2015.12.02

[검토의견]
요구사항은 결제 완료 후 처음 1회는 사용자가 시청하기 버튼을 터치하지 않고 자동으로 재생되도록 수정해 달라는 것입니다. 해당 사항에 대해서 민대표님께서 현행 유지하는 것으로 정리한다고 하셨습니다.

해당 이슈 종료합니다.

**Comment by MinJaeHun** [comment]
[2015.12.05] 캐스트이즈로 closing 처리 요청
- 플레이어 핸들링 이슈로 안드로이드 앱도 미적용
