### ISSUE TITLE
92. '컨텐츠의 타이틀이 길경우  타이틀이 말 줄임 처리되어있지 않음

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#17]
[보고일]
2015.11.19

[추적이슈번호]
92

[재현경로]
1. 씨앤앰 모바일 TV App 실행
2. 영화 카테고리 > 이달의 추천 VOD(특집)
3.컨텐츠 타이틀 확인

[기대결과]
'하단 타이틀은 롤링되지 않으며, 타이틀 표시 영역 내 타이틀을 모두 표시 하지 못할 경우 , 영역의 끝에서 말 줄임 처리 되어야함.

[현재증상]
'컨텐츠의 타이틀이 길경우  타이틀이 말 줄임 처리되어있지 않음..

**Comment by benjamincho** [comment]
[검토일]
2015.12.01

[검토의견]
0.2day	마이너	단위기능

**Comment by benjamincho** [comment]
메인화면 vod목록 하단의 컨텐츠 타이틀을 2줄에서 한줄로 재수정 합니다.

**Comment by benjamincho** [comment]
이슈종료합니다.

**Comment by MinJaeHun** [comment]
[2015.12.05 18:37] QC 팀 전달 issue list closed 완료
