### ISSUE TITLE
102. '일부 'TV전용 VOD컨텐츠 상세정보페이지에서   시청기기 에 'TV 모바일' 표기되어 보여짐.

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#18]
[보고일]
2015.11.20

[추적이슈번호]
102

[재현경로]
1.TV전용 컨텐츠 
2.상세정보 시청기기 확인
(ex:기생수 파트2)

[기대결과]
'TV 전용 컨텐츠 에 '모바일' 문구가 포함되지 않아야함.

[현재증상]
'일부 'TV전용 VOD컨텐츠 상세정보페이지에서   시청기기 에 'TV 모바일' 표기되어 보여짐.

**Comment by benjamincho** [comment]
[검토일]
2015.12.01

[검토의견]
1. 서버데이타 확인이 필요함.

0.5day	마이너	단위기능

**Comment by moriarty-dean** [comment]
상세정보 전문 요청시, 미디어 타입 [publicationRight]의 값이 '2', tv/모바일로 들어옴.

http://58.141.255.79:8080/HApplicationServer/getAssetInfo.xml?assetId=www.hchoice.co.kr%7CM4172624LSG357295601&assetProfile=9&terminalKey=A9D0D3B07231F38878AB0979D7C315A&version=1

**Comment by moriarty-dean** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<response><asset><HDContent>1</HDContent><UHDContent>0</UHDContent><assetId>www.hchoice.co.kr|M4172624LSG357295601</assetId><categoryAuthType>0</categoryAuthType><categoryId>713229</categoryId><copyProtection>1</copyProtection><director>야마자키 타카시</director><discountCouponMasterIdList><discountCouponMasterId>102</discountCouponMasterId><discountCouponMasterId>108</discountCouponMasterId></discountCouponMasterIdList><encryption>1</encryption><eventExList/><eventList/><extContentDomainId/><extContentId/><extContentMapped>0</extContentMapped><extContentType/><fileName>M4172624.mpg</fileName><genre>SF/환타지</genre><hot>0</hot><imageFileName>http://58.141.255.79:8080/PosterImage/big/M4172624LSG357295610.jpg</imageFileName><initialCategoryIdList><initialCategoryId>27282</initialCategoryId><initialCategoryId>304547</initialCategoryId></initialCategoryIdList><isNew>0</isNew><latestValidPurchasedTime/><licenseEnd>2016-02-11 23:59:59</licenseEnd><licenseStart>2015-11-12 00:00:00</licenseStart><logVisible>1</logVisible><new>0</new><nextWatch>0</nextWatch><nextWatchAssetId/><previewInfo><previewFileName/><previewRating/><previewRuningtime/></previewInfo><previewPeriod>300</previewPeriod><productList><product><bVATIncludedPrice>0</bVATIncludedPrice><casEntitlementId>200</casEntitlementId><casId/><casProductId>200</casProductId><discountCodeList/><discountEndTime/><discountPrice>0</discountPrice><discountRate>0</discountRate><discountTime/><goodId>1593027</goodId><jsCasPersonalBit/><listPrice>4500</listPrice><price>4500</price><productId>108</productId><productName>(HD)기생수 파트2</productName><productType>RVOD</productType><purchaseMethod>1</purchaseMethod><purchasedId>0</purchasedId><purchasedMethod>0</purchasedMethod><purchasedTime/><totalAssetCount>1</totalAssetCount><viewablePeriod>0000-00-03 00:00:00</viewablePeriod><viewablePeriodState>0</viewablePeriodState></product></productList><production>M4172624LSG3572956</production><promotionCopy/><promotionSticker>0</promotionSticker><publicationRight>2</publicationRight><purchaseLog><paymentType/><purchasedId>0</purchasedId><purchasedTime/></purchaseLog><rating>19</rating><reviewRatingCount>68</reviewRatingCount><reviewRatingTotal>316</reviewRatingTotal><runningTime>01:57</runningTime><seriesCurIndex>0</seriesCurIndex><seriesEndIndex>0</seriesEndIndex><seriesId/><seriesLink>0</seriesLink><seriesName/><seriesNextIndex>0</seriesNextIndex><seriesPrevIndex>0</seriesPrevIndex><seriesStartIndex>0</seriesStartIndex><seriesTotalAssetCount>0</seriesTotalAssetCount><smallImageFileName>http://58.141.255.79:8080/PosterImage/normal/M4172624LSG357295610.jpg</smallImageFileName><soundMix>STEREO</soundMix><starring>쇼메타니 쇼타,아베 사다오,하시모토 아이</starring><synopsis>가족과 친구를 잃은 신이치는 오른쪽이와 함께 인류를 위협하는 기생생물들을 없애기로 결심한다. 한편, 더욱 대범해진 기생생물들의 활동으로 인간사회에 그들의 존재가 알려지면서 경찰, 군대까지 동원된 기생생물과의 전쟁이 선포되는데...</synopsis><threeDimIndicator>00</threeDimIndicator><title>(HD)기생수 파트2</title><writer>야마자키 타카시</writer></asset><errorString/><resultCode>100</resultCode><transactionId null="true"/><version>1</version></response>

**Comment by benjamincho** [comment]
에어코드 서버담당자에게 문의메일 전송하였습니다.

**Comment by benjamincho** [comment]
서버 담당자 이상호 연구원과 확인하였으나 증상 재현되지 않습니다.
이슈 종료합니다.
