### ISSUE TITLE
103. VOD 구매목록 타이틀, 구매날짜, 가격정보등의 위치가 시나리오와 상이 함

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#19]
[보고일]
2015.11.20

[추적이슈번호]
103

[재현경로]
1. 레이어 메뉴 호출 > 마이 C&M
2. VOD 구매목록 탭
3. 구매 목록 내용 위치 확인

[기대결과]
VOD 구매목록 타이틀, 구매날짜, 가격정보등의 위치가 시나리오 대로 위치하여야 함

구매날짜 / 타이틀 / 기간
타이틀 / 기간 / 구매시간

순으로 표시 되어야 함

[현재증상]
VOD 구매목록 타이틀, 구매날짜, 가격정보등의 위치가 시나리오와 상이 함

구매날짜, 시간 / 아이콘 , 타이틀 / 기간,가격

순으로 표시 됨

**Comment by benjamincho** [comment]
[검토일]
2015.12.01

[검토의견]
1. 디자인가이드와 일치하게 작업함.
2. 수정은 단순기능
3. 목록상으로는 수정포인트 파악이 어려움

**Comment by benjamincho** [comment]
2015.12.02 민대표님과 이슈리뷰 중에 QC파트에서 기획서만 확인하고 코멘트 한 사항일 수 있다고 들었습니다.
일단 현행유지 하고 이슈 닫습니다.

**Comment by MinJaeHun** [comment]
[2015.12.05] 캐스트이즈로 closing 처리 요청

**Comment by MinJaeHun** [comment]
[2015.12.07] 캐스트이즈, 고도화 시점 반영으로 C&M과 협의

**Comment by benjamincho** [comment]
UI flipbook과 상이하지만 GUI 기준에 맞추어 구현되어 있음 (GUI가 후순위)
- 고객사 협의하여 closing 처리 요청 드립니다.

**Comment by benjamincho** [comment]
1월 고도화에 대상입니다.

**Comment by moriarty-dean** [comment]
VOD 구매목록 타이틀, 구매날짜, 가격정보등의 위치가 시나리오 대로 위치하여야 함

구매날짜 / 타이틀 / 기간
타이틀 / 기간 / 구매시간

순으로 표시 되어야 함

=================================

내용에 위와 같이 되어있는데, 

윗줄/아랫줄에 타이틀이랑 기간이 중복되고, 아이콘이랑 가격이 누락되어있습니다.

재확인 바랍니다.

**Comment by benjamincho** [comment]
기획문서(플립북)과 동일하게 수정하면 됩니다. gui가 후순위라고 합니다.

**Comment by benjamincho** [comment]
16/01/21 회의에서 고객사와 협의하여 이슈종료합니다.
