### ISSUE TITLE
107. 카테고리 내 하위 카테고리 순서 설정값대로 정렬되지 않음

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#21]
[보고일]
2015.11.20

[추적이슈번호]
107

[재현경로]
1. 영화, 애니키즈, TV다시보기, 성인 카테고리 진입
2. 하위 카테고리 GNB 클릭 
3. 정렬 순서 확인

[기대결과]
카테고리 내 하위 카테고리 순서 설정값과 일치하게 정렬 되어야 함

[현재증상]
카테고리 내 하위 카테고리 순서 설정값대로 정렬되지 않음
* CNM 카테고리 Manager Client로 확인

**Comment by benjamincho** [comment]
[검토일]
2015.12.02

[검토의견]
민재훈 대표님이 현행 카테고리 정렬 순서 확인해서 전달해 주시면 내용 적용하기로 하였습니다.

**Comment by benjamincho** [comment]
해당 이슈 기수정되어서 종료합니다.

**Comment by MinJaeHun** [comment]
[2015.12.08 11:09] QC팀 closing
