### ISSUE TITLE
109. 미리보기 3분 이상 시청되지 않음

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#22]
[보고일]
2015.11.20

[추적이슈번호]
109

[재현경로]
1. 미리보기 존재하는 VOD 상세 페이지 진입
2. 미리보기 시청시간 확인

[기대결과]
설정 된 미리보기 시간에 맞게 미리보기 시청 가능 하여야 함

[현재증상]
미리보기 3분 이상 시청되지 않음
실제 VOD 메타 데이터에서는 3분이상으로 보여주고 있음
(ex : 뷰티 인 사이드 - 5분으로 보여줌)

**Comment by benjamincho** [comment]
[검토일]
2015.12.02

[검토의견]
민재훈 대표님이 해당 기능의 연동 api 재확인 해서 전달해 주시면 확인해서 이슈 재검토 하기로 하였습니다.

**Comment by benjamincho** [comment]
이슈에서 제외합니다.
민대표님과 협의하였습니다.

**Comment by MinJaeHun** [comment]
[2015.12.05 18:37] QC 팀 전달 issue list closed 완료
