### ISSUE TITLE
117. 채널프로그램 녹화중인경우 녹화물 목록에 녹화중인 프로그램 리스트 노출되지 않음. *TV화면에선 녹화중 상태표시

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#23]
[보고일]
2015.11.20

[추적이슈번호]
117

[재현경로]
1. 레이어 메뉴 호출 > 채널가이드
2. 8 롯데홈쇼핑 > '침구' 채널 녹화중
3. 녹화물 목록 리스트 확인

[기대결과]
녹화가 진행중인경우 '녹화물 목록' 리스트에 녹화중인 프로그램 리스트 노출되어야함.

[현재증상]
채널프로그램 녹화중인경우 녹화물 목록에 녹화중인 프로그램 리스트 노출되지 않음.
*TV화면에선 녹화중 상태표시

**Comment by benjamincho** [comment]
[검토일]
2015.12.02

[검토의견]
사용자가 리모컨으로 녹화를 하더라도 셋탑에서 서버를 거쳐서 클라이언트에 정보가 전달되는 동안 딜레이가 발생해서 문제가 생길 소지가 있음으로 서버이슈여부를 판단해야 합니다.

민재훈 대표님이 다시한번 확인해 주시기로 하셨습니다.

**Comment by benjamincho** [comment]
1. 서버에서 녹화중이 프로그램목록을 내려주시 않고 있습니다.
2. 녹화물 목록중에 RecordEndTime 데이타가 없이 "NULL"로 들어오는 경우가 있습니다.
        {
        Channel_logo_img = http://58.141.255.69:8080/logo/154.png;
        RecordingType = 0;
        ChannelName = MBC_HD;
        RecordHD = YES;
        RecordDuration = 59;
        RecordProtection = N;
        ChannelId = 154;
        ProgramName = 화려한유혹(17회);
        RecordId = 19;
        RecordStartTime = 2015-11-30 22:00:00;
        RecordEndTime = NULL;
        ChannelNo = 11;
        SeriesId = NULL;
    }

**Comment by benjamincho** [comment]
민대표님과 협의하여 이슈에서 제외합니다.

**Comment by benjamincho** [comment]
가이드 요청을 위해서 이슈 다시 오픈합니다.

**Comment by MinJaeHun** [comment]
시나리오와 상이함
시나리오 상 녹화중인 프로그램은 녹화물목록에 노출되지 않으며, 녹화중지 시 녹화물목록으로 전환됨

[2015.12.04 18:37] QC 팀 전달 issue list closed 완료

**Comment by benjamincho** [comment]
해당이슈 종료합니다.
