### ISSUE TITLE
118. 구매 비밀번호 등록 페이지 내 입력 비밀번호가 상이 할 경우 비밀번호 입력 필드 초기화 시 구매 비밀번호 신규설정 입력필드로 커서 이동 되지 않음

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#24]
[보고일]
2015.11.22

[추적이슈번호]
118

[재현경로]
1. 셋탑박스 연동, 재연동 클릭
2. 구매 비밀번호 등록 페이지
3. 신규 비밀번호, 입력 비밀번호 상이하게 입력
4. 오류 팝업 발생 후 확인 클릭
5. 커서 위치 확인

[기대결과]
구매 비밀번호 등록 페이지 내 입력 비밀번호가 상이 할 경우 비밀번호 입력 필드 초기화 시 구매 비밀번호 신규설정 입력필드로 커서 이동 되지 않음

[현재증상]
구매 비밀번호 등록 페이지 내 입력 비밀번호가 상이 할 경우 비밀번호 입력 필드 초기화 시 구매 비밀번호 신규설정 입력필드로 커서 이동 되지 않음
구매 비밀번호 입력확인 필드로 이동 됨

**Comment by benjamincho** [comment]
[검토일]
2015.12.01

[검토의견]
0.2day	마이너	단위기능

**Comment by moriarty-dean** [comment]
80, 85에 의해, 오류 팝업 발생치 않고, 비밀번호 입력필드 입력시 초기화 시키고 있음.

**Comment by MinJaeHun** [comment]
[2015.12.05] 캐스트이즈로 closing 처리 또는 추가 설명 요청

**Comment by benjamincho** [comment]
85번과 동일이슈로 85번으로 수정작업하도록 하고 현이슈 종료합니다.

**Comment by MinJaeHun** [comment]
[2015.12.07] 캐스트이즈, 고도화 시점 반영하기로 C&M과 협의

**Comment by MinJaeHun** [comment]
[2015.12.08] QC, 이슈 재현됨
