### ISSUE TITLE
130. 성인 검색 제한 Off 상태에서 셋탑 연동 해제 후 재연동 시 검색제한 On으로 변경되지 않음

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#29]
[보고일]
2015.11.25

[추적이슈번호]
130

[재현경로]
1. 성인인증 완료 상태
2. 성인 검색 제한 Off 설정
3. 셋탑박스 페어링 해지
4. 성인 검색 제한 상태 확인

[기대결과]
성인 검색 제한 Off 상태에서 셋탑 연동 해제 후 재연동 시 성인인증도 해제 되어야 하며, 검색제한 On으로 변경되어야 함

[현재증상]
성인 검색 제한 Off 상태에서 셋탑 연동 해제 후 재연동 시 성인인증은 해제 되나, 검색 제한 상태 On으로 변경되지 않음

**Comment by benjamincho** [comment]
[검토일]
2015.12.01

[검토의견]
0.5day	마이너	단위기능

**Comment by benjamincho** [comment]
150. 동일한 이슈입니다.
정상동작입니다.
이슈 종료합니다.

**Comment by benjamincho** [comment]
민대표님이 이슈 재오픈 후 관련인원과 협의 진행하기로 하였습니다.

**Comment by benjamincho** [comment]
해당 이슈는 컨텐츠 검색시 설정상태와 관계없이 성인물이 검색되는 이슈입니다.
해당 내용 수정하였습니다.

**Comment by benjamincho** [comment]
해당 이슈 다시 정리하여서 수정합니다.
[재현경로]
1. 사용자가 페어링 해제
2. 좌측메뉴>설정>성인검색제한 확인

[현재증상]
항상 검색허용으로 되어 있음

[기대결과]
검색제한으로 초기화 되어야 함.

기대결과와 같이 수정하였습니다.

**Comment by MinJaeHun** [comment]
[2015.12.08] QC, 이슈 재현됨
