### ISSUE TITLE
133. 녹화예약 설정 후 '<(이전)'버튼 선택 후 해당 채널프로그램 재 진입 시 녹화예약 설정이 풀린상태로 보여짐

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#31]
[보고일]
2015.11.25

[추적이슈번호]
133

[재현경로]
1.채널가이드 > 프로그램 채널 선택 > 채널 SWIPE 후 녹화예약 설정 > 녹화예약 설정 표시 확인
2.'<(이전)' 버튼 선택 > 해당 채널 프로그램 재 진입 
2.녹화예약 설정 확인

[기대결과]
녹화예약 설정이 풀리지 않아야함.

[현재증상]
녹화예약 설정 후 '<(이전)'버튼 선택 후 해당 채널프로그램 재 진입 시 녹화예약 설정이 풀린상태로 보여짐

**Comment by benjamincho** [comment]
[검토일]
2015.12.01

[검토의견]
0.5day	마이너	공통기능

**Comment by benjamincho** [comment]
165와 동일이슈입니다. 수정하였습니다.

**Comment by MinJaeHun** [comment]
[2015.12.08 11:09] QC팀 closing
