### ISSUE TITLE
134. 셋탑이 전원이 'OFF' 된경우 녹화' 메뉴 진입 시 '녹화예약관리 , 녹화물목록' 에 '총-1개의 녹화예약 콘텐츠가 있습니다' 문구 표출됨

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#32]
[보고일]
2015.11.25

[추적이슈번호]
134

[재현경로]
1.패어링 상태에서 셋탑 전원 OFF
2.녹화 메뉴 진입
3.문구 확인

[기대결과]
셋탑 전원이 OFF 된경우 녹화메뉴 진입 시 그에 해당하는 팝업이 표출되어야함. 
(ex : 셋탑박스의 뒷 전원이 꺼져있거나 통신이 고르지못합니다..등)

[현재증상]
셋탑이 전원이 'OFF' 된경우 녹화' 메뉴 진입 시 '녹화예약관리 , 녹화물목록' 에 '총-1개의 녹화예약 콘텐츠가 있습니다' 문구 표출됨

**Comment by benjamincho** [comment]
[검토일]
2015.12.01

[검토의견]
0.2day	마이너	단위기능

**Comment by MinJaeHun** [comment]
오류 팝업 문구
- 셋탑박스의 뒷 전원이 꺼져있거나 통신이 고르지 못합니다.
STB 상태 확인 API
- slack으로 12.05 11:33 전달한 테스트 URL을 통해 확인

**Comment by benjamincho** [comment]
이슈 수정하여 종료합니다.
