### ISSUE TITLE
142. 'JTBC월정액 ' 결제 기능구현되지 않음 *영화 > 구매 테스트 > 07회 송곳

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#33]
[보고일]
2015.11.26

[추적이슈번호]
142

[재현경로]
1.영화 > 구매 테스트 > 07회 송곳
2.구매하기 > JTBC월정액 > 결제하기
3.동작 확인.

[기대결과]
'JTBC월정액 결제시  월정액 결제가 이루어져야함.

[현재증상]
'JTBC월정액 ' 결제 기능구현되지 않음
*영화 > 구매 테스트 > 07회 송곳

**Comment by benjamincho** [comment]
배정길 과장인 해당 기능 처리하였습니다.
해당이슈 종료합니다.

**Comment by benjamincho** [comment]
재현되어서 재오픈합니다.

**Comment by MinJaeHun** [comment]
추가 확인 부탁 드립니다. (QC issue list에는 open 상태)

**Comment by benjamincho** [comment]
해당이슈 종료합니다.
