### ISSUE TITLE
148. '[셋탑 전원 OFF] 상태에서 리모콘 메뉴 진입 후 채널 변경 시 팝업이 노출되지 않음. *채널가이드 메뉴에서 'TV로 시청 , 즉시녹화' 선택시 팝업노출되지않음.

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#37]
[보고일]
2015.11.27

[추적이슈번호]
148

[재현경로]
[셋탑 전원 OFF 상태]
1.리모콘 > 채널변경 선택
2.채널가이드 > 채널 상세정보 에서 'TV시청 및 즉시녹화등' 선택
3. 팝업문구 확인

[기대결과]
'셋탑 전원이 OFF 된경우 리모콘 메뉴에서 채널변경 시 '셋탑박스의 뒷 전원이 꺼져있거나 통신이 고르지못합니다' 팝업이 노출되어야함.

[현재증상]
'[셋탑 전원 OFF] 상태에서 리모콘 메뉴 진입 후 채널 변경 시 팝업이 노출되지 않음.
*채널가이드 메뉴에서 'TV로 시청 , 즉시녹화' 선택시 팝업노출되지않음.

**Comment by benjamincho** [comment]
[검토일]
2015.12.01

[검토의견]
0.2day	마이너	단위기능

**Comment by benjamincho** [comment]
해당이슈 안드로이드와 동일하게 수정하여 종료합니다.

**Comment by MinJaeHun** [comment]
[2015.12.08 11:09] QC팀 closing
