### ISSUE TITLE
150. '묶음 할인상품 구매 선택 후 구매하기 선택 시 상세정보 노출되지 않음.

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#38]
[보고일]
2015.11.29

[추적이슈번호]
150

[재현경로]
1.영화 > 구매테스트 > '더폰'
2.구매하기 > 묶음 할인상품 구매 > 구매하기
3.상세정보 확인

[기대결과]
'구매하기 선택 시 상세정보 및 구매 및 결제를 할수 있어야함.

[현재증상]
'묶음 할인상품 구매 선택 후 구매하기 선택 시 상세정보 노출되지 않음.

**Comment by benjamincho** [comment]
[검토일]
2015.12.01

[검토의견]
묶음 할인상품 구매에서 구매하기 선택시 상세정보가 노출되고 있습니다.

해당 이슈 종료합니다.

**Comment by benjamincho** [comment]
민대표님과 협의하여 이슈 재오픈합니다.
추가 확인이 필요합니다.
재현경로 요청할 예정입니다.

**Comment by MinJaeHun** [comment]
[2015.12.05] 캐스트이즈로 재현 경로 추가 문의

**Comment by benjamincho** [comment]
해당 이슈 수정 하였습니다.
