### ISSUE TITLE
152. VOD 구매목록 내 기간만료 된 목록 노출되지 않음

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#40]
[보고일]
2015.11.29

[추적이슈번호]
152.

[재현경로]
1. VOD 구매 목록
2. 기간만료 된 VOD 목록 노출 여부 확인

[기대결과]
구매시점부터 60일 동안 유지 되며 60일 경과 시 유효기간 만료 팝업을 표시하며 사용자에게 인지 시킴
* 유효기간 만료 팝업 내 [확인] 버튼 클릭 시 자동 삭제되지 않음

시청 기간이 60일 이상인 컨텐츠의 경우, 시청 기간 만큼 노출 되어야 며, 365일 상품은 365일 노출 되어야 함
* 60일 경과 후에도 유효기간 만료 팝업 발생하지 않아야 함

* 모바일 앱 및 셋탑에서 구매한 VOD의 모든 구매목록이 위와같이 동작하여야 함

[현재증상]
VOD 구매목록 내 기간만료 된 목록 노출되지 않음
모바일 구매목록 / TV 구매목록 동일 함

**Comment by benjamincho** [comment]
[검토일]
2015.12.01

[검토의견]
0.5day	마이너	단위기능

**Comment by benjamincho** [comment]
테스트 중 디즈니의 모든것을 선택하면 productType SVOD 이나 assetId가 없습니다.

```

                {

            viewablePeriod = 0000-00-00 00:00:00;

            paymentType = normal;

            seriesLink = 0;

            viewablePeriodState = 0;

            seriesCurIndex = 0;

            copyProtection = 0;

            encryption = 0;

            productId = 93326;

            HDContent = 0;

            productType = SVOD;

            purchasedId = 82768281;

            reviewRatingTotal = 0;

            purchaseDeviceType = 2;

            goodId = 93328;

            reviewRatingCount = 0;

            productAdultCode = 0;

            productName = 디즈니 VOD:디즈니 VOD의 모든 VOD 무한 시청;

            price = 5000;

            purchasedTime = 2015-11-27 11:52:55;

            categoryId = 0;

            purchaseMethod = 2;

        }
```

**Comment by benjamincho** [comment]
기간만료 로직 수정하였습니다.

**Comment by MinJaeHun** [comment]
본 이슈는 안드로이드에서 금요일 적용 완료된 사항입니다.
황민규 부장/김우담 과장 가이드 받으시면 되겠습니다.

**Comment by benjamincho** [comment]
해당 내용 가이드 받아서 수정하였습니다.
이슈 종료합니다.

**Comment by MinJaeHun** [comment]
[2015.12.08 11:09] QC팀 closing
