### ISSUE TITLE
153. TV 포인트 구매시 잔액이 결제 구매금액보다 많은경우에도 'TV포인트 회원가입 필요. TV에서 가입 가능합니다. 문구가 보여짐

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#41]
[보고일]
2015.11.29

[추적이슈번호]
153

[재현경로]
1.VOD컨텐츠 구하기 > TV 포인트 문구 확인

[기대결과]
TV포인트 잔액 금액이 VOD결제 구매보다 많을 경우 '보유포인트 차감결제 [TV 포인트 결제가능] 문구로 수정되어야함.

[현재증상]
TV 포인트 구매시 잔액이 결제 구매금액보다 많은경우에도 'TV포인트 회원가입 필요. TV에서 가입 가능합니다. 문구가 보여짐

**Comment by benjamincho** [comment]
[검토일]
2015.12.01

[검토의견]
0.2day	마이너	단위기능

**Comment by benjamincho** [comment]
TV포인트 구매 및 잔액에 대해서 증상재현을 위한 가이드가 필요합니다.

**Comment by MinJaeHun** [comment]
[2015.12.05] 캐스트이즈로 재현 경로 요청

**Comment by benjamincho** [comment]
기능 추가하여서 이슈 종료합니다.

**Comment by benjamincho** [comment]
수정완료 하여서 이슈종료합니다.
