### ISSUE TITLE
154. 페어링 해지 후 셋탑 재연동 시 시청목록 초기화되지 않음

### ISSUE THREAD

**Issue by moriarty-dean** [LambertPark/I_NScreen#42]
[보고일]
2015.11.29

[추적이슈번호]
154

[재현경로]
1. 시청목록 존재 상태
2. 셋탑 페어링 해지 및 재연동
   (동일 셋탑, 다른 셋탑)

[기대결과]
페어링 해지 후 셋탑 재연동 시 시청목록 초기화되어야 함
* 찜목록 시나리오와 동일한 형태로 구현 요망

[현재증상]
페어링 해지 후 셋탑 재연동 시 시청목록 초기화되지 않음
동일 셋탑 재연동 및 다른 셋탑 연동 시 동일 하게 초기화되지 않음

**Comment by moriarty-dean** [comment]
[검토일]
2015.12.01

[검토의견]
0.5day	마이너	단위기능

**Comment by benjamincho** [comment]
페어링 해지시 시청목록 삭제 처리
