### ISSUE TITLE
155. 묶음 상품 구매 완료 후 상세 페이지 진입 시 단일 VOD 상품의 구매완료 된 페이지 상태로 노출 됨

### ISSUE THREAD

**Issue by moriarty-dean** [LambertPark/I_NScreen#43]
[보고일]
2015.11.29

[추적이슈번호]
155

[재현경로]
1. 묶음 상품 구매 완료
(ex : 성난 변호사…)
2. 해당 VOD 상세 페이지 진입
3. 페이지 상태 확인

[기대결과]
묶음 상품 구매 완료 후 상세 페이지 진입 시 묶음상품 구매 완료 된 상태의 페이지로 진입 되어야 함

[현재증상]
묶음 상품 구매 완료 후 상세 페이지 진입 시 단일 VOD 상품의 구매완료 된 페이지 상태로 노출 됨

**Comment by moriarty-dean** [comment]
[검토일]
2015.12.01

[검토의견]
정상적으로 상세정보가 노출되고 있습니다.
정상동작임으로 이슈닫습니다.

**Comment by benjamincho** [comment]
재현되어서 재오픈합니다.

**Comment by benjamincho** [comment]
기수정하여서 이슈 종료합니다.
종료일은 금일로 처리합니다.
