### ISSUE TITLE
157. 셋탑 전원 Off상태일 경우 채널가이드 에서 채널프로그램 '녹화예약' 설정 시 App 강제종료 발생함.

### ISSUE THREAD

**Issue by moriarty-dean** [LambertPark/I_NScreen#45]
[보고일]
2015.11.29

[추적이슈번호]
157

[재현경로]
1. 페어링 된 셋탑 전원 Off상태
2. 채널가이드  > 채널프로그램 '녹화예약설정'
3. 상태 확인

[기대결과]
셋탑 전원 이 OFF 인 상태에 녹화예약 설정 시 App이 강제종료되지 않아야함

[현재증상]
셋탑 전원 Off상태일 경우 채널가이드 에서 채널프로그램 '녹화예약' 설정 시 App 강제종료 발생함.

**Comment by moriarty-dean** [comment]
[검토일]
2015.12.01

[검토의견]
0.5day	마이너	단위기능

**Comment by benjamincho** [comment]
해당 이슈 예약녹화관련 수정작업 후 재현되지 않습니다.
이슈 종료합니다.

**Comment by MinJaeHun** [comment]
[2015.12.08 11:09] QC팀 closing
