### ISSUE TITLE
158. 녹화예약관리 페이지 내 시리즈 녹화예약 목록선택 시 '내딸 ,금사월' 컨텐츠만 보여지고잇음.

### ISSUE THREAD

**Issue by moriarty-dean** [LambertPark/I_NScreen#46]
[보고일]
2015.11.29

[추적이슈번호]
158

[재현경로]
1. 시리즈 녹화물 예약 상태
2. 녹화 >  녹화 예약 목록 선택
*내딸 ,금사월 , 히든싱어4 목록 선택
3.녹화중인 채널 확인

[기대결과]
내 시리즈 녹화예약 목록선택 시 해당하는 채놀프로그램이 노출되어야함.

[현재증상]
녹화예약관리 페이지 내 시리즈 녹화예약 목록선택 시 '내딸 ,금사월' 컨텐츠만 보여지고잇음.

**Comment by moriarty-dean** [comment]
[검토일]
2015.12.01

[검토의견]
0.5day	마이너	단위기능

**Comment by moriarty-dean** [comment]
정확한 재현 경로  필요

**Comment by MinJaeHun** [comment]
[2015.12.08] QC, 이슈 재현됨
