### ISSUE TITLE
159. 녹화예약관리 페이지 내 시리즈 녹화예약 목록에서 Swipe 후 단편 및 시리즈 삭제 시 즉시 삭제가 이루어지지않으며 , App 재실행 후 녹화예약 관리 시리즈 항목 노출되고있음 *시리즈 항목 재 진입 시 정상 삭제되어있는것으로 보여짐'

### ISSUE THREAD

**Issue by moriarty-dean** [LambertPark/I_NScreen#47]
[보고일]
2015.11.29

[추적이슈번호]
159

[재현경로]
1. 시리즈 녹화물 예약 상태
2. 녹화 >  녹화 예약 목록 선택
*내딸 ,금사월 , 히든싱어4 목록 선택
3.Swip 후 단편 삭제 및 시리즈 삭제 선택
4. 확인

[기대결과]
단편 및 시리즈 삭제 시 정상적으로 삭제가 되어야함.

[현재증상]
녹화예약관리 페이지 내 시리즈 녹화예약 목록에서 Swipe 후 단편 및 시리즈 삭제 시 즉시 삭제가 이루어지지않으며 , App 재실행 후 녹화예약 관리 시리즈 항목 노출되고있음
*시리즈 항목 재 진입 시 정상 삭제되어있는것으로 보여짐'

**Comment by benjamincho** [comment]
[검토일]
2015.12.01

[검토의견]
0.5day	마이너	단위기능

**Comment by benjamincho** [comment]
민대표님과 협의하여 해당이슈 종료합니다.
