### ISSUE TITLE
161. 채널가이드, 채널 상세, 프로그램 검색 화면에서 STB통신 오류 발생 시 팝업 구현되지 않음

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#49]
[보고일]
2015.11.29

[추적이슈번호]
161

[재현경로]
1. 채널가이드 진입 및 프로그램명 검색
2. 오류 팝업 발생 시 팝업 내용 확인

[기대결과]
“셋탑박스와 통신이 끊어졌습니다. 
전원을 확인해 주세요.”
팝업 발생하여야 함

[현재증상]
채널가이드, 채널 상세, 프로그램 검색 화면에서 STB통신 오류 발생 시 팝업 구현되지 않음
셋탑 전원 꺼져있는 상태에서도 동일한 팝업 구현 되어야 함

**Comment by benjamincho** [comment]
[검토일]
2015.12.01

[검토의견]
1. 에러처리 관련 서버확인필요
2. 각 전문에서 에러코드가 내려오는지
3. 서버접속이 실패하는지 확인필요

0.5day	메이저	단위기능

**Comment by benjamincho** [comment]
민재훈 대표님에게 연동규격서를 받기로 하였습니다.

**Comment by MinJaeHun** [comment]
연동규격서 slack 및 메일로 전달 드렸습니다.
저도 모든 프로세스 이해하고 있지는 못하기 때문에 연동규격으로 해결이 안되면 캐스트이즈와 협의하시죠.

**Comment by benjamincho** [comment]
수정하였습니다.

**Comment by MinJaeHun** [comment]
[2015.12.08 11:09] QC팀 closing
