### ISSUE TITLE
162. 시청예약, 녹화예약 아이콘 동시표출 가능한지 확인 필요

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#50]
[보고일]
2015.11.29

[추적이슈번호]
162

[재현경로]
1. PVR 셋탑 페어링 상태
2. 채널가이드 > 일간 방송 목록
3. 동일 프로그램 시청예약, 녹화예약 버튼 클릭

[기대결과]
시청예약, 녹화예약 아이콘 동시표출 가능한지 확인 필요

[현재증상]
시청예약, 녹화예약 아이콘 동시표출 가능한지 확인 필요 (현재 녹화예약이 우선순위 높음)

**Comment by benjamincho** [comment]
[검토일]
2015.12.01

[검토의견]
디자인 가이드를 준수하여 작업하였으며, 해당 사항은 문의사항입니다.
문의 결과는 현재 시청예약, 녹화예약이 동시에 표시되지 않는 구조입니다.

해당 이슈 종료합니다.

**Comment by MinJaeHun** [comment]
[2015.12.05] 캐스트이즈로 closing 처리 요청

**Comment by benjamincho** [comment]
동시표출하도록 어쩌다가 수정해버렸습니다. 제길...
