### ISSUE TITLE
164. VOD 시청중 리모콘 메뉴에서 채널변경 시 해당 팝업 문구 노출되지 않음.

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#52]
[보고일]
2015.11.29

[추적이슈번호]
164

[재현경로]
1.패어링 된 셋탑에서 VOD 시청
2.레이어 메뉴 호출 > 리모콘 메뉴 > 채널변경
3.팝업 문구 확인

[기대결과]
VOD 시청중 리모콘 메뉴에서 채널 변경 시 'VOD시정중에는 채널을 변경할 수 없습니다. 팝업 문구가 노출되어야함.

[현재증상]
VOD 시청중 리모콘 메뉴에서 채널변경 시 해당 팝업 문구 노출되지 않음.

**Comment by benjamincho** [comment]
[검토일]
2015.12.01

[검토의견]
1. 서버데이타 확인이 필요함.
2. 서버데이타 문제 없으면 단순기능.
3. VOD를 tv로 보는 경우인지, 앱으로 보는 경우인지, 앱으로 vod시청시 좌측메뉴가 표시되는지 확인필요

1day

**Comment by benjamincho** [comment]
[검토일]
2015.12.02

민대표님께서 연동규격 전달하시면 다시 확인해서 재검토하기로 했습니다.

**Comment by MinJaeHun** [comment]
[2015.12.05 11:33] slack 및 메일을 통해 연동규격 가이드

**Comment by benjamincho** [comment]
전일 수정사항인데 클로우즈 하지 않아서 금일수정으로 종료합니다.
