### ISSUE TITLE
165. 녹화 예약 목록에 녹화중 표시 되지 않음

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#53]
[보고일]
2015.11.29

[추적이슈번호]
165

[재현경로]
1.녹화 > 녹화관리 > 녹화 예약관리
2.녹화중 표시 확인

[기대결과]
녹화예약관리 에 녹화중인 경우 '녹화중' 표시되어야함.

[현재증상]
녹화 예약 목록에 녹화중 표시 되지 않음

**Comment by benjamincho** [comment]
#23 117. 채널프로그램 녹화중인경우 녹화물 목록에 녹화중인 프로그램 리스트 노출되지 않음. *TV화면에선 녹화중 상태표시 

동일이슈입니다.

**Comment by MinJaeHun** [comment]
117항과 상이한 이슈 사항
- 녹화물 목록에 녹화중 표시가 되지 않아야 하지만, 녹화예약 목록에는 녹화 중 표시가 되어야 함

**Comment by MinJaeHun** [comment]
[2015.12.04 18:37] QC 팀 전달 issue list closed 완료
- 실제로는 closed 상태는 아니지만, 상품기획팀 이후 확인할 예정이라고 함 (re-open 될 가능성 있음)

**Comment by benjamincho** [comment]
수정하였습니다.

**Comment by benjamincho** [comment]
다른 이슈와 혼선이 있어서 이슈 히스토리 다시 정리합니다.

[재현경로 및 증상]
1. 사용자가 채널가이드에서 녹화를 선택하고 서버로 부터 성공메세지를 받아서 채널가이드는 화면이 갱신되었습니다.
2. 사용자가 녹화에서 녹화목록을 선택해서 현재 녹화중인 목록을 확인하였으나 표시가 되지 않습니다.

해당 케이스는 채널가이드에서 녹화요청하고 서버에서 응답을 정상적으로 받은 정보가 

녹화목록에서 데이타가 내려오지 않아서 발생하는 서버이슈입니다.

해당증상에 대해서 안드로이드도 동일하게 발생한다고 코멘트 받았습니다.

그래서 민대표님이 12-04일 qc코멘트로 이슈 종료한다고 하였습니다.

위의 히스토리에 코멘트가 나오고 수정내용이 나오는 것은 재현경로 1.과 관련해서 수정작업한 내용이 해당 이슈에 잘못 코멘트 된것입니다.

다시 이슈종료합니다.
