### ISSUE TITLE
168. 월정액 가입 완료 팝업 내용 구매 완료 팝업 내용으로 표시 됨

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#56]
[보고일]
2015.11.29

[추적이슈번호]
168

[재현경로]
1. 월정액 가입 가능 VOD
2.영화 > 구매테스트 > 우리집 꿀단지
2. 월정액 가입
3. 월정액 가입 완료 팝업 확인

[기대결과]
월정액 가입 완료 시 월정애 가입 완료 팝업 내용으로 표시 되어야 함
* 내용 문구 금일 박지혜 대리님께 전달 받은 메일 참고

[현재증상]
월정액 가입 완료 팝업 내용 구매 완료 팝업 내용으로 표시 됨

**Comment by benjamincho** [comment]
[검토일]
2015.12.01

[검토의견]
0.5day	마이너	단위기능

**Comment by benjamincho** [comment]
메일중에 해당 내용에 대한 것을 찾을 수가 없습니다.

**Comment by MinJaeHun** [comment]
[2015.12.06 01:26] 관련 메일은 조차장님 메일로 전달 드렸습니다.

**Comment by benjamincho** [comment]
해당 이슈 수정하였습니다.
마직막 테스트를 못했으나, 이상없겠죠....
이슈 종료합니다.
