### ISSUE TITLE
169. 월정액 가입 완료 후 가격 정보에 '이미 구매하셨습니다. 문구가 표기됨.

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#57]
[보고일]
2015.11.30

[추적이슈번호]
169

[재현경로]
1. 월정액 가입 가능 VOD
 2.영화 > 구매테스트 > 우리집 꿀단지
2. 월정액 가입 후 가격정보 문구 확인

[기대결과]
월정액 가입 완료 시 가격정보에 '해당 월정액에 가입하셨습니다. 문구로 표기되어야함.

[현재증상]
월정액 가입 완료 후 가격 정보에 '이미 구매하셨습니다. 문구가 표기됨.

**Comment by benjamincho** [comment]
161. 채널가이드, 채널 상세, 프로그램 검색 화면에서 STB통신 오류 발생 시 팝업 구현되지 않음과 동일한 이슈

**Comment by MinJaeHun** [comment]
161항 관련 사항 아닙니다.

**Comment by benjamincho** [comment]
코멘트가 잘못되어서 기수정 된 이슈를 금일로 재종료 처리 합니다.
