### ISSUE TITLE
172. 'VOD 명 검색 에서 시리즈전체회자 구매된 '신조협려 2014' 컨텐츠 상세정보 에 '구매하기' 버튼이 노출되는현상 *영화 > 구매테스트 > 신조협려 2014 > 시리즈 전체회자 구매 되어있음

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#60]
[보고일]
2015.11.30

[추적이슈번호]
172

[재현경로]
1.검색 > VOD 명 검색 > 신조협녀 2014 > 페이지 이동
2.확인

[기대결과]
'시리즈전체회차 구매된 경우 '신조협녀 2014 'OO회'는(은) TV에서 시청하실 수 있습니다. 문구가 보여져야함.

[현재증상]
'VOD 명 검색 에서 시리즈전체회자 구매된 '신조협려 2014' 컨텐츠 상세정보 에 '구매하기' 버튼이 노출되는현상
*영화 > 구매테스트 > 신조협려 2014 > 시리즈 전체회자 구매 되어있음

**Comment by benjamincho** [comment]
[검토일]
2015.12.01

[검토의견]
0.5day	마이너	단위기능

**Comment by moriarty-dean** [comment]
재현 경로가 필요합니다.

**Comment by benjamincho** [comment]
증상이 재현되지 않습니다.
