### ISSUE TITLE
174. '성인 카테고리 선택 후 '금주의신작영화' 선택 시 카테고리 내 VOD 목록 없을 경우 오류 팝업 구현되지 않음

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#62]
[보고일]
2015.11.30

[추적이슈번호]
174

[재현경로]
1.성인 > 금주의신작영화
2.페이지확인

[기대결과]
'금주의신작영화'depth 선택 시 해당 VOD컨텐츠 리스트 노출 및 팝업 노출되어야함.

[현재증상]
'성인 카테고리 선택 후 '금주의신작영화' 선택 시 카테고리 내 VOD 목록 없을 경우 오류 팝업 구현되지 않음

**Comment by benjamincho** [comment]
[검토일]
2015.12.01

[검토의견]
0.2day	마이너	단위기능

**Comment by benjamincho** [comment]
안드로이드와 동일하게 목록이 없으면 알림메세지 출력하도록 수정하였습니다.
이슈종료합니다.

**Comment by MinJaeHun** [comment]
[2015.12.08 11:09] QC팀 closing
