### ISSUE TITLE
178. 녹화예약관리 목록 내 녹화중인 목록 Swipe하여 녹화예약 취소 시 녹화예약 취소 가 이루어지지 않음

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#66]
[보고일]
2015.11.30

[추적이슈번호]
178

[재현경로]
1. PVR 셋탑 페어링 상태
2. 레이어 메뉴 호출 > 녹화 페이지 진입
3. 녹화예약관리 목록
4. 현재 녹화중인 목록 Swipe 후 녹화예약 취소 버튼 클릭

[기대결과]
녹화예약관리 목록 내 녹화중인 목록 Swipe하여 녹화예약취소 시  녹화 예약 취소가 이루어져야함.

[현재증상]
녹화예약관리 목록 내 녹화중인 목록 Swipe하여 녹화예약 취소 시 녹화예약 취소 가 이루어지지 않음.

**Comment by benjamincho** [comment]
[검토일]
2015.12.01

[검토의견]
0.5day	마이너	단위기능

**Comment by benjamincho** [comment]
민대표님과 협의하여 이슈종료합니다.

**Comment by MinJaeHun** [comment]
본 건은 일단 추가 검토 후 적용사항이며, closed 사항은 아닙니다.
다시 open 부탁 드립니다.
1차 등록 버전에서 제외될 수도 있습니다. (안드로이드도 1차 버전 제외됨)

**Comment by benjamincho** [comment]
녹화 예약, 최소관련 이슈 
1. 녹화요청 전문 호출시, resultCode가 207로 들어오는 경우가 종종 발생함.

ex)하단은 [kbs 나를 돌아봐] 녹화 요청시 로그로 아래와 같이 resultCode 값이 [207]로 들어옴.

http://58.141.255.80/smapplicationserver/SetRecordSeriesReserve.asp?ChannelId=152&StartTime=2015-12-11%2021%3A30%3A00&deviceId=BFB84ABE-1470-43DD-A5B8-ECB40F91CA9A&seriesId=M614021506&terminalKey=6840A4B3A93ADB1146F19A4E3D34439E&version=1

2015-12-10 11:08:18:383 I_NScreen[387:39542] 녹화예약 설정 시리즈 = [(
{
__name = response;
transactionId = 1;
resultCode = 207;
errString = Internal Processing Error;
version = SmartMobile_v1.0.0;
}

)]


2. 녹화>녹화 예약 관리

임의의 녹화 예약 등록된 시리즈 A를 [녹화 예약 취소(SetRecordCancelReserve)] 전문을 호출하여,

해당 A시리즈를 녹화 취소한 후에, [예약 녹화물 리스트(getrecordReservelist)] 전문을 호출시

삭제된 시리즈 A를 포함하여 예약 녹화물 리스트를 반환함.

다시한번 [예약 녹화물 리스트(getrecordReservelist)] 전문을 호출하면,

시리즈 A가 포함되지 않은 예약 녹화물 리스트를 반환함.

ex> 하단은 녹화예약된 [KBS2_HD 두리둥실 뭉게공항 2] 시리즈를 녹화 취소 한 후(1),
예약 녹화물 리스트를 조회 시 [KBS2_HD 두리둥실 뭉게공항 2]가 포함되어 들어왔다가 (2),
다시 예약 녹화물 리스트를 조회 시 [KBS2_HD 두리둥실 뭉게공항 2]가 제거된 목록을 반환(3)
하는 로그입니다.

(1) -------------------------------------------------------------------------------------------------------------------------------
2015-12-10 11:30:06.162 I_NScreen[411:47629] request : { URL: http://58.141.255.80/smapplicationserver/SetRecordCancelReserve.asp?ChannelId=152&ReserveCancel=1&StartTime=2015-12-11%2016%3A00%3A00&deviceId=BFB84ABE-1470-43DD-A5B8-ECB40F91CA9A&seriesId=M3130927342&terminalKey=6840A4B3A93ADB1146F19A4E3D34439E&version=1 }
2015-12-10 11:30:07:258 I_NScreen[411:47629] 녹화에약취소 = [(
{
__name = response;
transactionId = 1;
resultCode = 100;
version = SmartMobile_v1.0.0;
}

)}

(2) -------------------------------------------------------------------------------------------------------------------------------
2015-12-10 11:30:07.503 I_NScreen[411:47629] request : { URL: http://58.141.255.80/smapplicationserver/getrecordReservelist.asp?deviceId=BFB84ABE-1470-43DD-A5B8-ECB40F91CA9A&terminalKey=6840A4B3A93ADB1146F19A4E3D34439E&version=1 }
2015-12-10 11:30:09:212 I_NScreen[411:47629] 예약 녹화물 리스트 = [(
{
__name = response;
transactionId = 1;
resultCode = 100;
Reserve_Item = (
{
Channel_logo_img = http://58.141.255.69:8080/logo/152.png;
RecordingType = 0;
ChannelName = KBS2_HD;
RecordHD = YES;
RecordPaytype = N;
ChannelId = 152;
ProgramName = 두리둥실 뭉게공항 2(15회)(재);
OverlapId = 0;
RecordStartTime = 2015-12-11 16:00:00;
RecordStatus = N;
ChannelNo = 7;
SeriesId = M3130927342;
RecordEndTime = 2015-12-11 16:30:00;
}
,
{
Channel_logo_img = http://58.141.255.69:8080/logo/152.png;
RecordingType = 1;
ChannelName = KBS2_HD;
RecordHD = YES;
RecordPaytype = N;
ChannelId = 152;
ProgramName = 두리둥실 뭉게공항 2;
OverlapId = 0;
RecordStartTime = 0;
RecordStatus = N;
ChannelNo = 7;
SeriesId = M3130927342;
RecordEndTime = 2015-12-11 16:30:00;
}
,
{
Channel_logo_img = http://58.141.255.69:8080/logo/152.png;
RecordingType = 0;
ChannelName = KBS2_HD;
RecordHD = YES;
RecordPaytype = N;
ChannelId = 152;
ProgramName = TV소설 별이 되어 빛나리;
OverlapId = 0;
RecordStartTime = 2015-12-14 09:00:00;
RecordStatus = N;
ChannelNo = 7;
SeriesId = M614031796;
RecordEndTime = 2015-12-14 09:40:00;
}
,
{
Channel_logo_img = http://58.141.255.69:8080/logo/152.png;
RecordingType = 0;
ChannelName = KBS2_HD;
RecordHD = YES;
RecordPaytype = N;
ChannelId = 152;
ProgramName = TV소설 별이 되어 빛나리(74회);
OverlapId = 0;
RecordStartTime = 2015-12-11 09:00:00;
RecordStatus = N;
ChannelNo = 7;
SeriesId = M614031796;
RecordEndTime = 2015-12-11 09:40:00;
}
,
{
Channel_logo_img = http://58.141.255.69:8080/logo/152.png;
RecordingType = 1;
ChannelName = KBS2_HD;
RecordHD = YES;
RecordPaytype = N;
ChannelId = 152;
ProgramName = TV소설 별이 되어 빛나리;
OverlapId = 0;
RecordStartTime = 0;
RecordStatus = N;
ChannelNo = 7;
SeriesId = M614031796;
RecordEndTime = 2015-12-14 09:40:00;
}

);
    version = SmartMobile_v1.0.0;
}
)]

(3) -------------------------------------------------------------------------------------------------------------------------------
2015-12-10 11:31:04.625 I_NScreen[411:47629] request : { URL: http://58.141.255.80/smapplicationserver/getrecordReservelist.asp?deviceId=BFB84ABE-1470-43DD-A5B8-ECB40F91CA9A&terminalKey=6840A4B3A93ADB1146F19A4E3D34439E&version=1 }
2015-12-10 11:31:05:429 I_NScreen[411:47629] 예약 녹화물 리스트 = [(
{
__name = response;
transactionId = 1;
resultCode = 100;
Reserve_Item = (
{
Channel_logo_img = http://58.141.255.69:8080/logo/152.png;
RecordingType = 0;
ChannelName = KBS2_HD;
RecordHD = YES;
RecordPaytype = N;
ChannelId = 152;
ProgramName = TV소설 별이 되어 빛나리;
OverlapId = 0;
RecordStartTime = 2015-12-14 09:00:00;
RecordStatus = N;
ChannelNo = 7;
SeriesId = M614031796;
RecordEndTime = 2015-12-14 09:40:00;
}
,
{
Channel_logo_img = http://58.141.255.69:8080/logo/152.png;
RecordingType = 0;
ChannelName = KBS2_HD;
RecordHD = YES;
RecordPaytype = N;
ChannelId = 152;
ProgramName = TV소설 별이 되어 빛나리(74회);
OverlapId = 0;
RecordStartTime = 2015-12-11 09:00:00;
RecordStatus = N;
ChannelNo = 7;
SeriesId = M614031796;
RecordEndTime = 2015-12-11 09:40:00;
}
,
{
Channel_logo_img = http://58.141.255.69:8080/logo/152.png;
RecordingType = 1;
ChannelName = KBS2_HD;
RecordHD = YES;
RecordPaytype = N;
ChannelId = 152;
ProgramName = TV소설 별이 되어 빛나리;
OverlapId = 0;
RecordStartTime = 0;
RecordStatus = N;
ChannelNo = 7;
SeriesId = M614031796;
RecordEndTime = 2015-12-14 09:40:00;
}

);
    version = SmartMobile_v1.0.0;
}
)]

**Comment by benjamincho** [comment]
해당 이슈에 대해서 서버 이슈 등 복합적인 이유로 일단 유보하는 것으로 결정하였습니다.

**Comment by benjamincho** [comment]
서버이슈 - 데이터 갱신 안됨

**Comment by benjamincho** [comment]
테스터를 통해서 딜레이 주는 걸로 처리하는 걸로 정리하였습니다.
