### ISSUE TITLE
69. TV전용 콘텐츠 에 미리보기 버튼이 노출됨.

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#7]
[보고일]
2015.11.18

[추적이슈번호]
69

[재현경로]
1.씨앤앰모바일TV App 실행
2.(HD)투모로우랜드 콘텐츠 선택 > 많이 찾는 VOD (HD)케이크 콘텐츠 선택
3.버튼 확인

[기대결과]
TV 시청 한정 콘텐츠 인 경우, 미리보기 버튼 미노출되어야함.
*Flipbook 49page 참조

[현재증상]
TV전용 콘텐츠 에 미리보기 버튼이 노출됨.

**Comment by benjamincho** [comment]
[검토일]
2015.12.01

[검토의견]
1. 상세보기 공통처리로직 검토필요

1day 메이저 공통

**Comment by moriarty-dean** [comment]
publicationRight => 미디어 타입 : 1 - tv, 2 - tv/모바일
previewPeriod => 미리보기 시간

미디어 타입이 tv전용인 경우에, 미리보기 시간이 0이 아닌 경우가 있음.
미리보기 시간은 무시하고, 미디어 타입이 tv전용인 경우에 무조검 미리보기 숨김처리함.
