### ISSUE TITLE
182. TV다시보기 카테고리에서 스포츠레저 에 포함되어있는 컨텐츠 선택 시 App 강제종료 발생함.

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#70]
[보고일]
2015.12.01

[추적이슈번호]
182

[재현경로]
1.TV다시보기 > 스포츠레져
2.골프 > 레슨테라피 시즌2 Play Golf
3.등산,레져 > 호주 오프로드 챔피원십 2013 , FEI 어워즈…

[기대결과]
App 강제종료 발생하지 않아야하며 컨텐츠 진입이 되어야함.

[현재증상]
TV다시보기 카테고리에서 스포츠레저 에 포함되어있는 컨텐츠 선택 시 App 강제종료 발생함

**Comment by moriarty-dean** [comment]
증상 재현 안됨.

**Comment by MinJaeHun** [comment]
[2015.12.04 18:37] QC 팀 전달 issue list closed 완료
