### ISSUE TITLE
184. VOD 상세 페이지 내 많이찾는 VOD 클릭 및 뒤로가기 반복 시(5~10회) 앱 강제 종료 됨

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#72]
[보고일]
2015.12.01

[추적이슈번호]
184.

[재현경로]
1. VOD 상세 페이지 진입
2. 하단 많이 찾는 VOD 포스터 클릭 및 뒤로가기 반복

[기대결과]
VOD 상세 페이지 내 많이찾는 VOD 진입 및 뒤로가기 시 앱 강제종료되지 않아야 함

[현재증상]
VOD 상세 페이지 내 많이찾는 VOD 클릭 및 뒤로가기 반복 시(5~10회) 앱 강제 종료 됨

**Comment by moriarty-dean** [comment]
재현안됨

**Comment by benjamincho** [comment]
재현경로 재요청 하겠습니다.

**Comment by MinJaeHun** [comment]
안드로이드 동일현상 있어서 황민규 부장이 수정 처리하였습니다.
제가 재현경로 알고 있으니, 12.07 재현 경로 가이드 드리겠습니다.

**Comment by MinJaeHun** [comment]
[2015.12.07 18:43] QC팀 closed
