### ISSUE TITLE
187. 리모콘 메뉴 진입 시 현재시청채널 에 채널표시가 안되는현상

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#75]
[재현경로]
1.레이어 메뉴 호출
2.리모콘 메뉴 > 현재시청채널 번호 확인

[기대결과]
채널 재핑은 정상적으로 변경되어 라이브화면에 변경되어 보여지며 , 현재시청채널 번호에도 시청채널 정보가 노출되어야함.

[현재증상]
리모콘 메뉴 진입 시 현재시청채널 에 채널표시가 안되는현상

**Comment by benjamincho** [comment]
협의가 필요한 이슈로 전달받았습니다.

**Comment by benjamincho** [comment]
이슈 닫습니다.

**Comment by MinJaeHun** [comment]
본 건은 일단 추가 검토 후 적용사항이며, closed 사항은 아닙니다.
다시 open 부탁 드립니다.
1차 등록 버전에서 제외될 수도 있습니다. (안드로이드도 1차 버전 제외됨)
