### ISSUE TITLE
188. 리모콘 메뉴 진입 시 전체채널 프로그램명 모든항목에 녹화중으로 보여지고있음

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#76]
[재현경로]
1.레이어 메뉴 호출
2.리모콘 메뉴 > 전체채널 프로그램 확인

[기대결과]
현재 녹화중인 프로그램 정보에만 녹화중 표시가 되어야함.

[현재증상]
리모콘 메뉴 진입 시 전체채널 프로그램명 모든항목에 녹화중으로 보여지고있음

**Comment by benjamincho** [comment]
증상이 재현되지 않습니다.

**Comment by benjamincho** [comment]
해당 이슈 재현경로 가이드 받아서 수정하였습니다.

**Comment by MinJaeHun** [comment]
[2015.12.08 11:09] QC팀 closing
