### ISSUE TITLE
189. 무료 VOD 컨텐츠 인데도 불구하고 '구매하기' 버튼이 표출되며 구매하기 선택 시 상세정보에 구매상품선택 정보가 노출되지 않음 *검은집 , 오로라공주 등…

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#77]
[재현경로]
1.검색 > VOD명 검색
(ex : 검은집 , 오로라 공주.)
2.구매하기 버튼 확인

[기대결과]
무료 VOD 컨텐츠의 경우 '시청하기' 버튼이 표출되어야함.

[현재증상]
무료 VOD 컨텐츠 인데도 불구하고 '구매하기' 버튼이 표출되며 구매하기 선택 시 상세정보에 구매상품선택 정보가 노출되지 않음
*검은집 , 오로라공주 등…

**Comment by moriarty-dean** [comment]
재현경로 필요합니다.

**Comment by benjamincho** [comment]
증상이 재현되지 않습니다.

**Comment by benjamincho** [comment]
QC와 다시 테스트 하였는데 전일버전에서 재현되는 항목이 금일 개발버전에서 재현되지 않아
일단 이슈닫고 내일 테스트 항목에 포함하기로 하였습니다.
이슈 종료합니다.
