### ISSUE TITLE
80. 구매 비밀번호 신규설정 과 구매 비밀번호 입력확인' 에 비밀번호가 상이할경우 '설정완료' 버튼 비활성화 되지 않음.

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#9]
[보고일]
2015.11.

[추적이슈번호]
80

[재현경로]
1.씨앤앰모바일TV App 실행
2.레이어 메뉴 선택 > 셋탑박스 연동하기
3.'구매 비밀번호 신규설정 과 구매 비밀번호 입력확인' 에 비밀번호 다르게 입력
4.'다음 단계' 버튼 비활성화 확인

[기대결과]
'구매 비밀번호 신규설정 과 구매 비밀번호 입력확인' 에 비밀번호가 상이할경우 '설정완료' 버튼 비활성화 되어야함.

[현재증상]
'구매 비밀번호 신규설정 과 구매 비밀번호 입력확인' 에 비밀번호가 상이할경우 '설정완료' 버튼 비활성화 되지 않음.

**Comment by benjamincho** [comment]
[검토일]
2015.12.01

[검토의견]
0.2day	마이너	단위기능

**Comment by moriarty-dean** [comment]
수정완료
