### ISSUE TITLE
211. Creation Time 기준 15일 경과하지 않은 VOD 포스터에 [New] 스티커 표시되지 않음

### ISSUE THREAD

**Issue by benjamincho** [LambertPark/I_NScreen#94]
Creation Time 기준 15일 경과하지 않은 VOD 포스터에 [New] 스티커 표시되지 않음
(ex : 영화 > 금주의 신작영화 내 포스터 확인)

**Comment by moriarty-dean** [comment]
영화 > 금주의 신작영화에 사용되는 전문(getContentGroupList)에서 
들어오는 데이터상에 프로모션 값이 new로 들어오지 않는 항목 존재함.
ex)
{
            assetNew = 0;
            imageFileName = http://58.141.255.79:8080/PosterImage/big/M4145356LSG352594810.jpg;
            rating = 19;
            runningTime = 01:43;
            smallImageFileName = http://58.141.255.79:8080/PosterImage/normal/M4145356LSG352594810.jpg;
            primaryAssetId = www.hchoice.co.kr|M4145356LSG352594801;
            title = 도프;
            synopsis = 캘리포니아의 험한 동네에 사는 말콤은 90년대 힙합과 패션을 즐기며 명문대 입학을 꿈꾼다. 어느 날, 그는 친구 집, 디기와 함께 파티에 참석했다가 마약사건에 휘말리는데...;
            assetBundle = 0;
            likedCount = 0;
            mobilePublicationRight = 1;
            starring = 샤메익 무어,토니 레볼로리,키어시 클레몬스,라킴 마이어에 참석했다가 마약사건에 휘말리는데...;
            assetBundle = 0;
            likedCount = 0;
            mobilePublicationRight = 1;
            starring = 샤메익 무어,토니 레볼로리,키어시 클레몬스,라킴 마이어\354스,블레이크 앤더슨,디안드레 본즈,줄리안 브랜드,퀸시 브라운;
            assetFree = 2;
            episodePeerExistence = 0;
            assetSeriesLink = 0;
            isLiked = 0;
            production = M4145356LSG3525948;
            UHDAssetCount = 0;
            isFavorite = 0;
            director = 릭 파무이와;
            HDAssetCount = 1;
            SDAssetCount = 0;
            genre = 코미디;
            promotionSticker = 0;
            reviewRating = 0.0;
            assetHot = 0;
            categoryId = 1582063;
            contentGroupId = 507972;
        }
